version: '1.25.0'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"  # Changed external port to 3307 to avoid conflict

  backend:
    image: my-spring-boot-app:latest
    container_name: backend-container
    environment:
      DATABASE_HOST: mysql
      DATABASE_NAME: appdb
      DATABASE_USER: user
      DATABASE_PASSWORD: password
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    entrypoint: sh -c "until nc -z -v -w30 mysql 3306; do echo 'Waiting for database connection...'; sleep 5; done && java -jar /app/app.jar"

volumes:
  db-data:

